<?php

namespace ContainerRrbDNxo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UKaI849Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UKaI849' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UKaI849'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.UKaI849.App\\Entity\\Bookings', NULL, 'Cannot autowire service ".service_locator.UKaI849": it needs an instance of "App\\Entity\\Bookings" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'booking' => 'App\\Entity\\Bookings',
            'entityManager' => '?',
        ]);
    }
}
