<?php

namespace ContainerRrbDNxo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S8qFsrJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S8qFsrJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S8qFsrJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.S8qFsrJ.App\\Entity\\Bookings', NULL, 'Cannot autowire service ".service_locator.S8qFsrJ": it needs an instance of "App\\Entity\\Bookings" but this type has been excluded in "config/services.yaml".'],
        ], [
            'booking' => 'App\\Entity\\Bookings',
        ]);
    }
}
