<?php

namespace ContainerRrbDNxo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O3cX2VmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o3cX2Vm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o3cX2Vm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'student' => ['privates', '.errored..service_locator.o3cX2Vm.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.o3cX2Vm": it needs an instance of "App\\Entity\\Student" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'student' => 'App\\Entity\\Student',
        ]);
    }
}
