<?php

namespace ContainerRrbDNxo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RlP127DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rlP127D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rlP127D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookingsRepository' => ['privates', 'App\\Repository\\BookingsRepository', 'getBookingsRepositoryService', true],
        ], [
            'bookingsRepository' => 'App\\Repository\\BookingsRepository',
        ]);
    }
}
