<?php

namespace ContainerRrbDNxo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookings2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UKaI849.App\Entity\Bookings' shared service.
     *
     * @return \App\Entity\Bookings
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UKaI849": it needs an instance of "App\\Entity\\Bookings" but this type has been excluded in "config/services.yaml".');
    }
}
