<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRrbDNxo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRrbDNxo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRrbDNxo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRrbDNxo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRrbDNxo\App_KernelDevDebugContainer([
    'container.build_hash' => 'RrbDNxo',
    'container.build_id' => 'e36688fc',
    'container.build_time' => 1717864387,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRrbDNxo');
